# Generated by Django 3.0.2 on 2020-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200602_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_information',
            name='property_type',
            field=models.CharField(choices=[('Builder Floor', 'Builder Floor'), ('Residential Plot', 'Residential Plot'), ('Commercial Shops', 'Commercial Shops')], default='Residentail Plot', max_length=100),
        ),
    ]
