# Generated by Django 3.0.2 on 2020-06-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_auto_20200606_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_information',
            name='BHK',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('other', 'other')], default=1, max_length=100),
        ),
    ]
